theme = "GeeksAreForLife"
baseURL = "https://www.geeksareforlife.com/"
languageCode = "en-gb"
title = "GeeksAreForLife"

enableGitInfo = true

sectionPagesMenu = "main"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"

# Code higlighting settings
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[[menu.main]]
  identifier = "now"
  name = "Now"
  url = "/now/"
  weight = -110

[author]
  name = "James Hayward"
  email = "hi@geeksareforlife.com"

[params]
  copyright = "Copyright © 2020, James Hayward, all rights reserved."
  description = "GeeksAreForLife - random musings of a geek getting old"

  twitter = "@geeksareforlife"

  mainSections = ["posts"]

  [[params.relme]]
    cta = "Go To GitHub"
    icon = "fab fa-github"
    href = "https://www.github.com/geeksareforlife"

  [[params.relme]]
    cta = "Go To Twitter"
    icon = "fab fa-twitter"
    href = "https://www.twitter.com/geeksareforlife"

  [[params.relme]]
    cta = "Go To Keybase"
    icon = "fab fa-keybase"
    href = "https://www.keybase.io/geeksareforlife"

  [[params.relme]]
    cta = "Email Me"
    icon = "far fa-at"
    href = "mailto:hi@geeksareforlife.com"
